spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect
    hibernate:
      ddl-auto: create-drop
      show-sql: true
  datasource:
    url: jdbc:mariadb://localhost:3306/lmsdiogo
    username: root
    password: mypass


